# Generated by Django 5.2.7 on 2025-12-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoverificacion',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
